project:
  type: website

website:
  title: "Your Own Statistician"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: team.qmd
        text: "Team"
      
  sidebar:    
    style: "docked"
    search: true
    contents:
      - section: "Data science with R and RStudior"
      - r_rstudio/1_intro.qmd
      - r_rstudio/2_first_steps.qmd
      - r_rstudio/99_learning_r_links.qmd
      - section: ""
      - section: "Data visualisation"
      - data_viz/1_viz_principles.qmd
      - section: ""
      - section: "Journal club"
      - journal_club/1_explain_predict.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

